name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Code Quality
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: |
            **/uv.lock
            **/pyproject.toml

      - name: Install dependencies for ta-lib
        run: |
          curl -L -O https://github.com/ta-lib/ta-lib/releases/download/v0.6.4/ta-lib_0.6.4_amd64.deb &&
          sudo dpkg -i ta-lib_0.6.4_amd64.deb

      - name: Install project with dev dependencies
        run: uv sync --all-extras --dev

      - name: Check formatting with Black
        run: uv run black --check .

      - name: Check linting with pylint
        run: uv run pylint src/ --fail-under=8

      - name: Run pytest
        run: uv run pytest tests -v